name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ arshiaaflaki }}
          password: ${{ dckr_pat_t2IKU9j5wiMo3eaixLFtEa4cbc0 }} 

      - name: Build Docker image
        run: docker build -t nyt -f Dockerfile .

      - name: Push Docker image to registry
        run: docker push nyt
