name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.arshiaaflaki }}
      DOCKER_PASSWORD: ${{ secrets.Ar8569844 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check CI workflow status
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
            echo "CI workflow succeeded. Proceeding with deployment."
          else
            echo "CI workflow did not succeed. Skipping deployment."
            exit 78  # Skip the job if CI did not succeed
          fi

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.arshiaaflaki }}
          password: ${{ secrets.Ar8569844 }}

      - name: Build Docker image
        run: docker build -t nyt -f Dockerfile .

      - name: Push Docker image to registry
        run: docker push nyt
