name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.arshiaaflaki }}
      DOCKER_PASSWORD: ${{ secrets.Ar8569844 }}

    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.Ar8569844 }} | docker login -u ${{ secrets.arshiaaflaki }} --password-stdin


      - name: Build Docker image
        run: docker build -t nyt -f Dockerfile .

      - name: Push Docker image to registry
        run: docker push nyt
